<%@page contentType="text/html" pageEncoding="UTF-8" %>
<!--- Footer -->
<footer class="footer">
    <div class="container-fluid padding">
        <div class="row text-center">
            <div class="col-md-6">
                <hr class="light">
                <h5>Kontakt os</h5>
                <hr class="light">
                <p>+45 45 87 10 01</p>
                <p>Fog-carporte@fog.dk</p>
                <p>Firskovvej 20</p>
                <p>2800 Kongens Lyngby</p>
            </div>
            <div class="col-md-6">
                <hr class="light">
                <h5>Åbningstider</h5>
                <hr class="light">
                <p>Hverdage: 6:00 - 17:30</p>
                <p>Lørdag: 08:00 - 14:00</p>
                <p>Søndag & helligdage: 10:00 - 14:00</p>
            </div>
            <div class="col-12">
                <hr class="light-100">
                <h5>GRUPPE 10<a href="https://github.com/thorchris/Fog-carport"><i class="fab fa-github"></i></a></h5>
            </div>
        </div>
    </div>
</footer>
</body>
</html>