<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="styles/styles.css">

    <title>Fog carport</title>
</head>

<nav class="navbar-expand-lg navbar">
    <a class="navbar-brand" href="FrontController?taget=redirect&modtagerside=index">FOG CARPORT</a>
    <ul class="navbar-nav ml-auto">
        <li><a class="nav-link" href="FrontController?taget=redirect&modtagerside=register">DESIGN CARPORT</a></li>
        <li class="nav-item "><a class="nav-link " href="FrontController?taget=logout">KONTAKT OS</a> </li>
        <li class="nav-item "><a class="nav-link " href="FrontController?taget=redirect&modtagerside=checkout">OM OS</a> </li>
        <li class="nav-item "><a class="nav-link " href="FrontController?taget=redirect&modtagerside=checkout">LOGIN</a> </li>
    </ul>
</nav>
<body>