@startuml
Title CreateOrder
actor User
boundary Design.jsp
participant FrontController
participant Command
participant CreateOrder
participant LogicFacade
participant DataMapper
database FogCarporte


User -> Design.jsp : Send til sælger
Design.jsp -> FrontController : doPost()
FrontController -> FrontController: proscessRequest()
FrontController -> Command: from()
Command --> FrontController: Object = CreateOrder
FrontController -> CreateOrder: Execute()
CreateOrder -> LogicFacade: createOrder()\ncreateCustomerDesign()
LogicFacade -> DataMapper: createCustomerDesign()
DataMapper -> FogCarporte: executeQuery()
FogCarporte --> DataMapper: OK
DataMapper --> LogicFacade: OK
LogicFacade --> CreateOrder: OK
CreateOrder --> FrontController: OK
FrontController --> Design.jsp: forward()
Design.jsp --> User: Order er modtaget

@enduml